spring.application.name=physio-backend
server.port=${PORT:8080}
# SMTP Server
spring.mail.host=smtp.gmail.com
spring.mail.port=465

# Clinic email (sender)
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
resend.api.key=${RESEND_API_KEY}
# SMTP Security
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
